### ISSUE TITLE
崩了

### ISSUE THREAD

**Issue by showdy** [LRH1993/SmartRecom#5]
跑着跑着崩了...好多地方需要优化, 哥们有你忙的了 ^^

**Comment by showdy** [comment]
FATAL EXCEPTION: main
                                                 Process: com.lvr.threerecom, PID: 8342
                                                 java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
                                                     at java.util.ArrayList.get(ArrayList.java:411)
                                                     at com.lvr.threerecom.service.MediaPlayService.playSong(MediaPlayService.java:145)
                                                     at com.lvr.threerecom.ui.music.MusicRankingListDetailActivity.onItemClick(MusicRankingListDetailActivity.java:204)
                                                     at com.lvr.threerecom.adapter.MusicRankingListDetailAdapter$1.onClick(MusicRankingListDetailAdapter.java:68)
                                                     at android.view.View.performClick(View.java:5646)
                                                     at android.view.View$PerformClick.run(View.java:22450)
                                                     at android.os.Handler.handleCallback(Handler.java:755)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:156)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by LRH1993** [comment]
嗯，音乐加载是有问题，之前就遇到，还没改
